name: xleaflet
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  - ninja
  # Host dependencies
  - cppzmq
  - xproperty
  - nlohmann_json
  - xwidgets>=0.30,<0.31
  - xtensor>=0.27,<0.28
  # Test dependencies
  - doctest
  - pybind11=2.7.1
  - pybind11_json=0.2.11
  - ipyleaflet=0.14.0

