name: xleaflet
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  # Host dependencies
  - xeus=2.0.0
  - cppzmq
  - xproperty=0.11.0
  - xwidgets=0.26.0
  - xtensor=0.23.0
  # Test dependencies
  - pybind11=2.7.1
  - pybind11_json=0.2.11
  - ipyleaflet=0.14.0

