name: xleaflet
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  - ninja
  # Host dependencies
  - cppzmq
  - xproperty=0.11.0
  - xwidgets=0.27.1
  - xtensor=0.24.3
  # Test dependencies
  - pybind11=2.7.1
  - pybind11_json=0.2.11
  - ipyleaflet=0.14.0

